# All common configration places on single place 
# Eureka cleint configration 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
